name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Droplet
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

          echo "Connecting and running deployment commands..."
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            export PATH=/home/meet/.nvm/versions/node/v22.17.1/bin:$PATH
            cd /home/meet/app/ms
            git pull origin main
            yarn cache clean
            yarn install  
            yarn build
            /home/meet/scripts/ms/copy.sh
          EOF
